[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mrg-helm"
version = "2.0.1"
dependencies = [
  "typer",
  "protobuf",
  "nanopb",
  "grpcio-tools",
  "platformio",
  "typing_extensions",
  "vserial"
]
requires-python = ">=3.8"
authors = [
  {name = "Sean Fish", email = "seantfish@gmail.com"},
]
description = "Automated Helm Interface"
readme = "README.md"

[project.optional-dependencies]

[project.urls]

[project.scripts]
mrg-helm = "mrg_helm.app:cli"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
dependencies = ["hatch-build-scripts", "protobuf", "nanopb", "grpcio-tools"]
include = [
  "mrg_helm/*.py",
  "mrg_helm/sim/**",
  "mrg_helm/pb/**",
  "mrg_helm/utils/**",
  "mrg_helm/comm/**",
  "firmware",
  "platformio.ini",
  "proto",
]
artifacts = ["mrg_helm/pb/**"]

[[tool.hatch.build.targets.wheel.hooks.build-scripts.scripts]]
commands = [
    "python mrg_helm/utils/protogen.py"
]
clean_artifacts = false
